version: '3.8'
services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: portfolio
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env.example
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - '5173:4173'
    env_file:
      - ./frontend/.env.example
    depends_on:
      - backend

volumes:
  pgdata: